---
# tasks file for mongodb
- name: config | Configuring MongoDB
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config }}"
  become: true
  register: mongodb_configured
  notify:
    - restart mongod
